version: '3.7'
services:
  proxy:
    restart: always
    container_name: diego-rabbit-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - diego-rabbitmq-container

  diego-rabbitmq-service:
    image: rabbitmq
    container_name: diego-rabbitmq-service
    environment: 
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: admin
     RABBITMQ_DEFAULT_VHOST: /
    ports:
     - "15672:15672"
     - "5672:5672" 

  diego-rabbitmq-container:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: diego-rabbitmq-container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/diegorabbitmq
    tty: true
    links:
      - diego-rabbitmq-service
    environment:
      PORT: 8080