version: '3.7'
services:
  proxy:
    restart: always
    container_name: diego-elasticsearch-container-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - diego-demo-elasticsearch-container

  diego-demo-elasticsearch-container:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: diego-demo-elasticsearch-container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/elasticsearch
    links:
     - diego-demo-elasticsearch
    tty: true
    environment:
      PORT: 8080

  diego-demo-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"