version: '3.7'
services:
  diego-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: diego-elasticsearch
    environment:
      - node.name=diego-elasticsearch
      - discovery.seed_hosts=diego-elasticsearch-second
      - cluster.initial_master_nodes=diego-elasticsearch,diego-elasticsearch-second
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  
  diego-elasticsearch-second:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: diego-elasticsearch-second
    environment:
      - node.name=diego-elasticsearch-second
      - discovery.seed_hosts=diego-elasticsearch
      - cluster.initial_master_nodes=diego-elasticsearch,diego-elasticsearch-second
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"   

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet: